modLoader="javafml"
loaderVersion="[43,)"
license="Apache License 2.0"
[[mods]]
modId="safespawn"
version="${version}"
displayName="SafeSpawn"
authors="smbarbour"
description='''
Creates a safe area at spawn
'''
[[dependencies.safespawn]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.safespawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"